### ISSUE TITLE
How to remotely connect to mysql and restart a service in your lemp.

### ISSUE THREAD

**Issue by hoanghiep1x0** [noamanahmed/LEMP#26]
Hi can you tell me how to remotely connect to mysql and restart a web service in your lemp.
It helps me a lot but I am still stuck on some questions.

@help @noamanahmed

**Comment by noamanahmed** [comment]
What stack? PHP or node. There is a restart-site script.

Remote connection is something that would NEVER be allowed.

There is a possibility to add OpenVPN or wire guard setup to access it securely. There is alot of security issues involved in opening it publicly

But if this is something you definitely want. You can bind mysql address to public ip and use ufw allow command to expose it on the internet.

**Comment by hoanghiep1x0** [comment]
Exactly as you said. Disallow remote connection but there are some way like public ip to allow remote into mysql. I'm looking for a way to use this to make pushing data easier. However, there is a lot of documentation and you are not sure how to get your library up and running. If possible you can spend a little time teaching people to read and learn more about mysql or mongodb remote connection.
Above is just wish if yes I think it is very helpful  ! Really thanks for your library it helps me a lot.

**Comment by hoanghiep1x0** [comment]
I am using strapi with mysql.
But my own project usually write it with nodejs and mongodb.
It took me 2 days to learn about your library about permission to access ssh and connect to upload data to sever.
Currently there are some problems such as wanting to install pm2 start but don't know how. I will learn more about how to get started on specific projects step by step.

**Comment by ghost** [comment]
You don't need to use PM2. Node JS process will be run using systemd scripts. This allows more granular control and will also allow alerts in a Monit in future too. The concept of whole architecture is that the person having the user privileges is just to upload and deploy code.

Regarding documentation, I haven't updated it in a long time.

**Comment by hoanghiep1x0** [comment]
I really want to share this library to my friends as well as those who need it I see a lot of people need it. They should be known and used with guidance. Because there are definitely users like me stuck at ssh. Or stuck at the database access step. Or they have trouble using systemclt to start when they're getting used to pm2 or nodemon.
Because this repository is quite new to people like me and it focuses a lot of knowledge to be able to use it methodically and effectively. I would love to offer you a cup of coffee to thank you for your contributions.

**Comment by ghost** [comment]
You don't need to use PM2. Node JS process will be run using systemd scripts. This allows more granular control and will also allow alerts in a Monit in future too. The concept of whole architecture is that the person having the user privileges is just to upload and deploy code.

Regarding documentation, I haven't updated it in a long time. 

You can contact me over LinkedIn ( the link is in my profile description) and I can guide you how to set it up.
