### ISSUE TITLE
When I upload the file with nodejs the nginx 502 error.

### ISSUE THREAD

**Issue by hoanghiep1x0** [noamanahmed/LEMP#27]
When I upload the file, nginx error 502.
And when i try to fix nginx using online guide and restart nginx i get ssl error
How to fix and fix Let's Encrypt ssl . error

**Comment by hoanghiep1x0** [comment]
When running with node sever.js right in the project it works upload normally.
But when switching it runs with systemctl enable admin-site.service
  systemctl enable admin-site.service
  systemctl start admin-site.service
.... Now it can't upload files to the server...
A 502 error returned I tried many times but failed maybe it's related to permissions.

**Comment by hoanghiep1x0** [comment]
I tried to fix it and found it working fine with pm2 start sever.js as root.
Can you show me how to fix it to use with your project i am testing admin with nodejs strapi

**Comment by ghost** [comment]
No. This is not built for PM2. Forget PM2. Use restart-site script to restart server
